# Generated by Django 4.1.7 on 2023-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('City', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Population', models.IntegerField()),
            ],
        ),
    ]
