# Generated by Django 4.1.7 on 2023-03-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('population_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='City_Info',
        ),
    ]
